#!/usr/bin/env python3

import argparse
import json
import os
import sqlite3
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from threading import Lock

from batch_common import CpuAllocator, default_workers, detect_visible_cpu_ids, parse_csv_items, print_status, run_backend


DB_LOCK = Lock()


def build_arg_parser():
    parser = argparse.ArgumentParser(description="Batch ReDoS verification")
    parser.add_argument("db_file", help="SQLite database generated by Gen.py")
    parser.add_argument("max_size_kb", type=int, help="Maximum payload size in KB")
    parser.add_argument("match_mode", choices=["0", "1"], help="0=partial, 1=full")
    parser.add_argument("--engines", help="Comma-separated engine ids; default: all available engines")
    parser.add_argument("--workers", type=int, default=default_workers(), help="Concurrent workers")
    parser.add_argument("--timeout-seconds", type=int, help="Per-engine timeout in seconds")
    parser.add_argument("--cpu-cores", type=int, help="CPU cores passed to runexec")
    parser.add_argument("--memory-mb", type=int, help="Memory limit in MB passed to runexec")
    parser.add_argument(
        "--candidate-policy",
        choices=["recommended", "all"],
        default="recommended",
        help="recommended: only run the recommended candidate; all: run all stored candidates"
    )
    parser.add_argument("--repeat-override", type=int, help="Override repeat count for legacy attacks")
    parser.add_argument("--max-repeat-times", type=int, help="Upper bound for legacy repeats")
    return parser


def ensure_positive(value, field_name):
    if value is None:
        return None
    if value <= 0:
        raise ValueError(f"{field_name} must be greater than 0.")
    return value


def ensure_database_exists(db_path):
    if not os.path.exists(db_path):
        raise FileNotFoundError(f"Database file not found: {db_path}")


def normalize_selected_engines(meta, requested_engines):
    available = [engine["id"] for engine in meta.get("engines", []) if engine.get("available")]
    if requested_engines:
        selected = parse_csv_items(requested_engines)
    else:
        selected = available

    if not selected:
        raise ValueError("No engines selected.")

    unsupported = [engine_id for engine_id in selected if engine_id not in available]
    if unsupported:
        raise ValueError(f"Unsupported or unavailable engines: {', '.join(unsupported)}")
    return selected


def setup_verify_table(db_path):
    conn = sqlite3.connect(db_path)
    try:
        conn.executescript(
            """
            DROP TABLE IF EXISTS verify_result;
            CREATE TABLE verify_result (
                tool TEXT NOT NULL,
                id INTEGER NOT NULL,
                engine TEXT NOT NULL,
                candidate_id TEXT NOT NULL,
                status TEXT NOT NULL,
                elapsed_ms REAL,
                time REAL,
                time_source TEXT,
                walltime_ms REAL,
                cputime_ms REAL,
                memory_bytes INTEGER,
                error_type TEXT,
                termination_reason TEXT,
                return_value INTEGER,
                match_count INTEGER,
                stdout TEXT,
                stderr TEXT,
                raw_output TEXT,
                logs_json TEXT,
                attack_source_json TEXT,
                PRIMARY KEY (tool, id, engine, candidate_id),
                FOREIGN KEY (id) REFERENCES regexes(id)
            );
            """
        )
        conn.commit()
    finally:
        conn.close()


def upsert_meta(conn, key, value):
    conn.execute(
        """
        INSERT INTO batch_meta (key, value_json, updated_at)
        VALUES (?, ?, CURRENT_TIMESTAMP)
        ON CONFLICT(key) DO UPDATE SET value_json=excluded.value_json, updated_at=CURRENT_TIMESTAMP
        """,
        (key, json.dumps(value, ensure_ascii=False))
    )


def load_attack_jobs(db_path, candidate_policy):
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    try:
        attack_rows = conn.execute(
            """
            SELECT ar.tool, ar.id, ar.prefix, ar.infix, ar.suffix, ar.repeat_times, r.regex
            FROM attack_result ar
            JOIN regexes r ON r.id = ar.id
            WHERE ar.status = 'completed' AND ar.is_redos = 1
            ORDER BY ar.id, ar.tool
            """
        ).fetchall()

        jobs = []
        for row in attack_rows:
            candidates = conn.execute(
                """
                SELECT candidate_id, candidate_label, is_recommended, attack_type, full_text, prefix, infix, suffix, repeat_times
                FROM attack_candidate
                WHERE tool = ? AND id = ?
                ORDER BY is_recommended DESC, candidate_id ASC
                """,
                (row["tool"], row["id"])
            ).fetchall()

            if candidates:
                selected_candidates = list(candidates)
                if candidate_policy == "recommended":
                    selected_candidates = [candidate for candidate in candidates if candidate["is_recommended"]]
                    if not selected_candidates:
                        selected_candidates = [candidates[0]]

                for candidate in selected_candidates:
                    if candidate["attack_type"] == "fullText":
                        attack = {"fullText": candidate["full_text"]}
                    else:
                        attack = {
                            "prefix": candidate["prefix"],
                            "infix": candidate["infix"],
                            "suffix": candidate["suffix"],
                            "repeat_times": candidate["repeat_times"]
                        }
                    jobs.append({
                        "tool": row["tool"],
                        "regex_id": row["id"],
                        "regex": row["regex"],
                        "candidate_id": candidate["candidate_id"],
                        "candidate_label": candidate["candidate_label"],
                        "attack": attack
                    })
                continue

            jobs.append({
                "tool": row["tool"],
                "regex_id": row["id"],
                "regex": row["regex"],
                "candidate_id": "legacy",
                "candidate_label": "Legacy attack",
                "attack": {
                    "prefix": row["prefix"] or "",
                    "infix": row["infix"] or "",
                    "suffix": row["suffix"] or "",
                    "repeat_times": row["repeat_times"] if row["repeat_times"] is not None else -1
                }
            })
        return jobs
    finally:
        conn.close()


def write_verify_result(db_path, job, engine_id, result):
    output = result.get("output") if isinstance(result.get("output"), dict) else {}
    metadata = result.get("metadata") if isinstance(result.get("metadata"), dict) else {}
    error = result.get("error") if isinstance(result.get("error"), dict) else {}
    elapsed_ms = output.get("elapsed_ms")
    if elapsed_ms is None:
        elapsed_ms = result.get("elapsedMs")
    effective_time = output.get("time")
    if effective_time is None:
        effective_time = error.get("time")
    if effective_time is None:
        effective_time = elapsed_ms
    time_source = output.get("time_source")
    if time_source is None:
        time_source = error.get("timeSource")
    walltime_ms = output.get("walltime_ms")
    if walltime_ms is None:
        walltime_ms = error.get("walltimeMs")
    cputime_ms = output.get("cputime_ms")
    if cputime_ms is None:
        cputime_ms = error.get("cputimeMs")
    memory_bytes = output.get("memory_bytes")
    if memory_bytes is None:
        memory_bytes = error.get("memoryBytes")
    with DB_LOCK:
        conn = sqlite3.connect(db_path)
        try:
            conn.execute(
                """
                INSERT OR REPLACE INTO verify_result
                (tool, id, engine, candidate_id, status, elapsed_ms, time, time_source, walltime_ms, cputime_ms, memory_bytes, error_type, termination_reason, return_value, match_count, stdout, stderr, raw_output, logs_json, attack_source_json)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    job["tool"],
                    job["regex_id"],
                    engine_id,
                    job["candidate_id"],
                    result.get("status", "failed"),
                    elapsed_ms,
                    effective_time,
                    time_source,
                    walltime_ms,
                    cputime_ms,
                    memory_bytes,
                    error.get("type"),
                    error.get("terminationReason"),
                    error.get("returnValue"),
                    output.get("match_count"),
                    result.get("stdout", ""),
                    result.get("stderr", ""),
                    result.get("rawOutput"),
                    json.dumps(result.get("logs") or [], ensure_ascii=False),
                    json.dumps(metadata.get("attackSource") or {}, ensure_ascii=False)
                )
            )
            conn.commit()
        finally:
            conn.close()


def process_task(db_path, job, engine_id, args, cpu_allocator):
    attack_source = {
        "toolId": job["tool"],
        "candidateId": job["candidate_id"],
        "candidateLabel": job["candidate_label"]
    }
    payload = {
        "regex": job["regex"],
        "engineId": engine_id,
        "attack": job["attack"],
        "matchMode": int(args.match_mode),
        "maxAttackLength": args.max_size_kb * 1024,
        "attackSource": attack_source
    }
    if args.timeout_seconds is not None:
        payload["timeoutSeconds"] = args.timeout_seconds
    if args.cpu_cores is not None:
        payload["cpuCores"] = args.cpu_cores
    if args.memory_mb is not None:
        payload["memoryMB"] = args.memory_mb
    if args.repeat_override is not None:
        payload["repeatOverride"] = args.repeat_override
    if args.max_repeat_times is not None:
        payload["maxRepeatTimes"] = args.max_repeat_times

    allocated_cores = None
    if cpu_allocator and args.cpu_cores is not None:
        allocated_cores = cpu_allocator.acquire(args.cpu_cores)
        payload["cores"] = allocated_cores

    try:
        result = run_backend("run-engine", payload)
    finally:
        if cpu_allocator and allocated_cores:
            cpu_allocator.release(allocated_cores)

    write_verify_result(db_path, job, engine_id, result)
    print_status(
        f"[Verify] regex={job['regex_id']} tool={job['tool']} candidate={job['candidate_id']} engine={engine_id} status={result.get('status', 'failed')}"
    )
    return result


def summarize(db_path):
    conn = sqlite3.connect(db_path)
    try:
        total = conn.execute("SELECT COUNT(*) FROM verify_result").fetchone()[0]
        failures = conn.execute("SELECT COUNT(*) FROM verify_result WHERE status = 'failed'").fetchone()[0]
        inconclusive = conn.execute("SELECT COUNT(*) FROM verify_result WHERE status = 'inconclusive'").fetchone()[0]
        slowest = conn.execute(
            """
            SELECT tool, id, engine, candidate_id, COALESCE(time, elapsed_ms, -1) AS effective_time
            FROM verify_result
            ORDER BY COALESCE(time, elapsed_ms, -1) DESC
            LIMIT 3
            """
        ).fetchall()
    finally:
        conn.close()

    print_status(f"[Verify] completed results={total} failures={failures} inconclusive={inconclusive}")
    for tool, regex_id, engine, candidate_id, effective_time in slowest:
        print_status(f"[Verify] slowest regex={regex_id} tool={tool} engine={engine} candidate={candidate_id} time={effective_time}")


def main():
    parser = build_arg_parser()
    args = parser.parse_args()

    try:
        ensure_positive(args.max_size_kb, "max_size_kb")
        ensure_positive(args.workers, "workers")
        ensure_positive(args.timeout_seconds, "timeout-seconds")
        ensure_positive(args.cpu_cores, "cpu-cores")
        ensure_positive(args.memory_mb, "memory-mb")
        ensure_positive(args.repeat_override, "repeat-override")
        ensure_positive(args.max_repeat_times, "max-repeat-times")
        ensure_database_exists(args.db_file)
    except (ValueError, FileNotFoundError) as exc:
        print(str(exc), file=sys.stderr)
        return 1

    visible_cpu_ids = detect_visible_cpu_ids()
    if args.cpu_cores is not None and args.cpu_cores > len(visible_cpu_ids):
        print(
            f"Requested {args.cpu_cores} CPU cores, but only {len(visible_cpu_ids)} are visible in this container.",
            file=sys.stderr
        )
        return 1

    try:
        meta = run_backend("meta")
        selected_engines = normalize_selected_engines(meta, args.engines)
    except (RuntimeError, ValueError) as exc:
        print(str(exc), file=sys.stderr)
        return 1

    setup_verify_table(args.db_file)
    conn = sqlite3.connect(args.db_file)
    try:
        upsert_meta(conn, "verify_args", vars(args))
        upsert_meta(conn, "verify_meta_snapshot", meta)
        upsert_meta(conn, "verify_runtime_cpu_info", {
            "visibleCpuIds": visible_cpu_ids,
            "requestedCpuCores": args.cpu_cores
        })
        conn.commit()
    finally:
        conn.close()

    jobs = load_attack_jobs(args.db_file, args.candidate_policy)
    if not jobs:
        print_status("[Verify] no attack candidates found")
        return 0

    cpu_allocator = CpuAllocator(visible_cpu_ids) if args.cpu_cores is not None else None

    print_status(
        f"[Verify] attacks={len(jobs)} engines={len(selected_engines)} workers={args.workers} "
        f"candidate_policy={args.candidate_policy} visible_cpus={len(visible_cpu_ids)} "
        f"requested_cpu_cores={args.cpu_cores or 'none'}"
    )

    failures = 0
    with ThreadPoolExecutor(max_workers=args.workers) as executor:
        futures = [
            executor.submit(process_task, args.db_file, job, engine_id, args, cpu_allocator)
            for job in jobs
            for engine_id in selected_engines
        ]
        for future in as_completed(futures):
            try:
                future.result()
            except Exception as exc:
                failures += 1
                print_status(f"[Verify] task failed: {exc}")

    summarize(args.db_file)
    return 0 if failures == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
